.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH px2ansi-rs-list 1  "px2ansi-rs-list " 
.SH NAME
px2ansi\-rs\-list \- List entries in the index
.SH SYNOPSIS
\fBpx2ansi\-rs\-list\fR [\fB\-c\fR|\fB\-\-count\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List entries in the index
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-count\fR \fI<COUNT>\fR
Number of entries to show (omit to show all)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
