.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH px2ansi-rs-index 1  "px2ansi-rs-index " 
.SH NAME
px2ansi\-rs\-index \- Create a JSON index of a directory
.SH SYNOPSIS
\fBpx2ansi\-rs\-index\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIDIR\fR> 
.SH DESCRIPTION
Create a JSON index of a directory
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<OUTPUT>\fR
Path to save the JSON index
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIDIR\fR>
Directory to scan
