#![allow(clippy::multiple_crate_versions)]
use image::{DynamicImage, GenericImageView, Rgba};
use std::io::Write;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputMode {
    Ansi,    // Standard half-blocks
    Unicode, // Full blocks or specialized chars (like pokemon-colorscripts)
}

/// Renders an image into the terminal using ANSI escape sequences.
///
/// Depending on the `mode`, this will either:
/// - **Ansi**: Squash two vertical pixels into one character cell using half-blocks (▀/▄).
/// - **Unicode**: Render each pixel as a double-width square block (██) for a retro look.
/// # Errors
///
/// This function returns an [`std::io::Result::Err`] if:
/// * The provided output writer `out` fails to write the generated bytes.
/// * There is an issue flushing the buffer to the terminal or file.
///
/// Note: This function does not currently validate image dimensions; however,
/// passing extremely large images may result in performance issues depending
/// on the writer's capability.
pub fn write_ansi_art<W: Write>(
    img: &DynamicImage,
    out: &mut W,
    mode: OutputMode,
    full_block: bool,
) -> std::io::Result<()> {
    let (width, height) = img.dimensions();

    match mode {
        OutputMode::Ansi => {
            // Ansi mode uses a "vertical pairing" trick to double the effective resolution.
            // By using the foreground for the top pixel and background for the bottom,
            // we can fit two pixels into a single character's space.
            for y in (0..height).step_by(2) {
                for x in 0..width {
                    let top = img.get_pixel(x, y);
                    let bot = if y + 1 < height {
                        img.get_pixel(x, y + 1)
                    } else {
                        Rgba([0, 0, 0, 0])
                    };
                    write_half_block(out, top, bot)?;
                }
                writeln!(out, "\x1b[0m")?;
            }
        }
        OutputMode::Unicode => {
            if full_block {
                // The "Pokemon-Colorscripts" look: 1 pixel = 2 wide characters
                for y in 0..height {
                    for x in 0..width {
                        let px = img.get_pixel(x, y);
                        write_full_block(out, px)?;
                    }
                    writeln!(out, "\x1b[0m")?;
                }
            } else {
                // The "Crisp Unicode" look: Uses half-blocks but on
                // a per-row basis or specialized logic
                for y in (0..height).step_by(2) {
                    for x in 0..width {
                        let top = img.get_pixel(x, y);
                        let bot = if y + 1 < height {
                            img.get_pixel(x, y + 1)
                        } else {
                            Rgba([0, 0, 0, 0])
                        };
                        write_half_block(out, top, bot)?;
                    }
                    writeln!(out, "\x1b[0m")?;
                }
            }
        }
    }
    Ok(())
}

/// A low-level helper that squashes two vertical pixels into a single terminal character cell.
///
/// It uses the 'upper half block' character (▀) and clever color manipulation:
/// - The **foreground** color is set to the `top` pixel.
/// - The **background** color is set to the `bot` pixel.
///
/// If one of the pixels is transparent (alpha = 0), it switches to a half-block
/// or space with a transparent background to let the terminal's own theme show through.
fn write_half_block<W: Write>(out: &mut W, top: Rgba<u8>, bot: Rgba<u8>) -> std::io::Result<()> {
    match (top[3] > 0, bot[3] > 0) {
        (true, true) => write!(
            out,
            "\x1b[38;2;{};{};{}m\x1b[48;2;{};{};{}m▀",
            top[0], top[1], top[2], bot[0], bot[1], bot[2]
        ),
        (true, false) => write!(out, "\x1b[38;2;{};{};{}m\x1b[49m▀", top[0], top[1], top[2]),
        (false, true) => write!(out, "\x1b[38;2;{};{};{}m\x1b[49m▄", bot[0], bot[1], bot[2]),
        (false, false) => write!(out, "\x1b[0m "),
    }
}

/// Renders a single pixel as a wide, solid block using two 'full block' characters (██).
///
/// Since terminal character cells are usually twice as tall as they are wide,
/// printing two characters for every one pixel preserves a square aspect ratio.
/// This is the technique used by tools like `pokemon-colorscripts`.
///
/// If the pixel is transparent, it simply prints two spaces.
fn write_full_block<W: Write>(out: &mut W, px: Rgba<u8>) -> std::io::Result<()> {
    if px[3] > 0 {
        // Print TWO blocks for every ONE pixel
        write!(out, "\x1b[38;2;{};{};{}m██", px[0], px[1], px[2])
    } else {
        write!(out, "  ") // Two spaces
    }
}
